import { writeFileSync } from "node:fs";
import path from "node:path";
import type { ServiceDef } from "./config";

export interface EnvEntry {
  name: string; // forkspace service name, e.g. "mysql"
  def: ServiceDef;
  hostPort: number;
}

function applyTemplate(tpl: string, vars: Record<string, string>): string {
  return tpl.replace(/\{(\w+)\}/g, (_, k) => vars[k] ?? `{${k}}`);
}

/**
 * Render the env file for an instance. Always emits:
 *   FORKSPACE_ENV, FORKSPACE_FORK, FORKSPACE_PROJECT
 *   FORKSPACE_<SERVICE>_PORT / _HOST for each managed service
 * plus any per-service `exports` templates from forkspace.yml.
 */
export function renderEnvFile(opts: {
  env: string;
  fork: string | null;
  project: string;
  entries: EnvEntry[];
}): string {
  const lines: string[] = [
    `# generated by forkspace — do not edit`,
    `FORKSPACE_ENV=${opts.env}`,
    `FORKSPACE_FORK=${opts.fork ?? ""}`,
    `FORKSPACE_PROJECT=${opts.project}`,
  ];
  for (const e of opts.entries) {
    const upper = e.name.toUpperCase().replace(/[^A-Z0-9]/g, "_");
    lines.push(`FORKSPACE_${upper}_HOST=127.0.0.1`);
    lines.push(`FORKSPACE_${upper}_PORT=${e.hostPort}`);
    const vars = {
      host: "127.0.0.1",
      port: String(e.hostPort),
      service: e.name,
    };
    for (const [k, tpl] of Object.entries(e.def.exports)) {
      lines.push(`${k}=${applyTemplate(tpl, vars)}`);
    }
  }
  return lines.join("\n") + "\n";
}

export function envFileName(env: string, fork: string | null): string {
  return fork ? `.env.forkspace.${env}.${fork}` : `.env.forkspace.${env}`;
}

export function writeEnvFile(
  root: string,
  env: string,
  fork: string | null,
  content: string
): string {
  const rel = envFileName(env, fork);
  writeFileSync(path.join(root, rel), content);
  return rel;
}

/** Parse a rendered env file body into a record (for hook subprocess env). */
export function envToRecord(content: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const line of content.split("\n")) {
    const m = line.match(/^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);
    if (m) out[m[1]] = m[2];
  }
  return out;
}
