import { writeFileSync } from "node:fs";
import path from "node:path";
import type { ServiceDef } from "./config";

export interface EnvEntry {
  name: string; // forkspace service name, e.g. "mysql"
  def: ServiceDef;
  hostPort: number;
}

export interface AllocationEntry {
  name: string;
  hostPort: number;
}

export interface BaselineExports {
  ns: string;
  ports: Record<string, number>;
}

function applyTemplate(tpl: string, vars: Record<string, string>): string {
  return tpl.replace(/\{(\w+)\}/g, (_, k) => vars[k] ?? `{${k}}`);
}

function templateVars(opts: {
  ns: string;
  nsDash: string;
  host: string;
  port: number;
  service: string;
}): Record<string, string> {
  const { ns, nsDash, host, port, service } = opts;
  return {
    host,
    port: String(port),
    service,
    ns,
    _ns: ns ? `_${ns}` : "",
    ns_: ns ? `${ns}_` : "",
    nsdash: nsDash,
    _nsdash: nsDash ? `-${nsDash}` : "",
    nsdash_: nsDash ? `${nsDash}-` : "",
  };
}

/**
 * Render the env file for an instance. Always emits:
 *   FORKSPACE_ENV, FORKSPACE_FORK, FORKSPACE_PROJECT, FORKSPACE_NS
 *   FORKSPACE_NS_DASH (forks only, when non-empty)
 *   FORKSPACE_INVOKE_DIR (directory where the CLI was invoked)
 *   FORKSPACE_<SERVICE>_PORT / _HOST for each managed service
 *   FORKSPACE_<ALLOC>_PORT for each named allocation
 *   FORKSPACE_BASELINE_NS and FORKSPACE_BASELINE_<SERVICE>_HOST/_PORT (forks only)
 * plus any per-service `exports` templates from forkspace.yml.
 */
export function renderEnvFile(opts: {
  env: string;
  fork: string | null;
  project: string;
  ns: string;
  nsDash?: string;
  invokeDir: string;
  entries: EnvEntry[];
  allocations?: AllocationEntry[];
  baseline?: BaselineExports;
}): string {
  const nsDash = opts.nsDash ?? "";
  const lines: string[] = [
    `# generated by forkspace — do not edit`,
    `FORKSPACE_ENV=${opts.env}`,
    `FORKSPACE_FORK=${opts.fork ?? ""}`,
    `FORKSPACE_PROJECT=${opts.project}`,
    `FORKSPACE_NS=${opts.ns}`,
    `FORKSPACE_INVOKE_DIR=${opts.invokeDir}`,
  ];
  if (nsDash) {
    lines.push(`FORKSPACE_NS_DASH=${nsDash}`);
  }
  if (opts.baseline) {
    lines.push(`FORKSPACE_BASELINE_NS=${opts.baseline.ns}`);
    for (const [name, port] of Object.entries(opts.baseline.ports)) {
      const upper = name.toUpperCase().replace(/[^A-Z0-9]/g, "_");
      lines.push(`FORKSPACE_BASELINE_${upper}_HOST=127.0.0.1`);
      lines.push(`FORKSPACE_BASELINE_${upper}_PORT=${port}`);
    }
  }
  for (const e of opts.entries) {
    const upper = e.name.toUpperCase().replace(/[^A-Z0-9]/g, "_");
    lines.push(`FORKSPACE_${upper}_HOST=127.0.0.1`);
    lines.push(`FORKSPACE_${upper}_PORT=${e.hostPort}`);
    const vars = templateVars({
      ns: opts.ns,
      nsDash,
      host: "127.0.0.1",
      port: e.hostPort,
      service: e.name,
    });
    for (const [k, tpl] of Object.entries(e.def.exports)) {
      lines.push(`${k}=${applyTemplate(tpl, vars)}`);
    }
  }
  for (const a of opts.allocations ?? []) {
    const upper = a.name.toUpperCase().replace(/[^A-Z0-9]/g, "_");
    lines.push(`FORKSPACE_${upper}_PORT=${a.hostPort}`);
  }
  return lines.join("\n") + "\n";
}

export function envFileName(env: string, fork: string | null): string {
  return fork ? `.env.forkspace.${env}.${fork}` : `.env.forkspace.${env}`;
}

export function writeEnvFile(
  root: string,
  env: string,
  fork: string | null,
  content: string
): string {
  const rel = envFileName(env, fork);
  writeFileSync(path.join(root, rel), content);
  return rel;
}

/** Parse a rendered env file body into a record (for hook subprocess env). */
export function envToRecord(content: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const line of content.split("\n")) {
    const m = line.match(/^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);
    if (m) out[m[1]] = m[2];
  }
  return out;
}
